name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # Use only one version

      - name: Setup Node
        uses: actions/setup-node@v3  # Use only one version

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3  # Use only one version
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3  # Use only one version
        with:
          name: production-files
          path: ./dist

      - name: Verify files are downloaded
        run: ls -al ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Or use a custom PAT if necessary
          publish_dir: ./dist

      - name: Clear cache (optional but useful if deploying issues persist)
        run: |
          git clean -fdx
          git reset --hard HEAD
